spring.application.name=vehicle-service

server.port = 8084

spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#eureka.client.enabled=false
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:seed.sql
spring.jpa.defer-datasource-initialization=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
