spring.application.name=user-role-service

server.port=8092

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_role_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Seed Data
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:seed.sql
spring.jpa.defer-datasource-initialization=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# JWT
jwt.secret=ThisIsADevelopmentSecretKeyThatIsAtLeast32CharactersLong123
jwt.expiration=3600000